### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by alsmola**

### CODE REVIEW

**Comment by nathanleiby** [comment]
not sure how to review this, but assuming our dependent apps still build, lgtm

**Comment by alsmola** [comment]
@nathanleiby they will need to update the version in their glide/godep setup, right?

**Comment by alsmola** [comment]
I have a follow-up branch that updates catapult, at least.

**Comment by nathanleiby** [comment]
For sure-- they will continue running with their current setup unless we explicitly update

**Pull request merged**
